spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopapi?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    database: mysql
    hibernate:
      # DB 테이블 자동 생성 옵션
      ddl-auto: update
    # log
    show-sql: true
    properties:
      hibernate:
        # 로그 예쁘게 찍기
        format_sql: true
        highlight_sql: true
        # 방언
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

# 파일업로드 저장 경로
shopapi.upload.path: upload

# log
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
    org.springframework.security.web: trace

# jsessionid 파라미터로 전달X
server:
  servlet:
    session:
      tracking-modes: cookie